####### Explicit

# Model params
model: vit_small_patch16_224.augreg_in21k
img_size: 384
batch_size: 128

# Data and augmentation
data: /workspace/datasets/ImageNet

# Optimization
epochs: 64
cooldown_epochs: 0
warmup_epochs: 2
opt: sgd
momentum: 0.9
lr: 0.03
warmup_lr: 1e-6
min_lr: 5e-6
sched: cosine
sched_epochwise: False

# Misc
amp: True
amp_dtype: bfloat16
weight_decay: 0
log_wandb: True
project: wintome-dinat-s-IN1k
output: /workspace/akane/runs



###### Other defaults
aa: null
amp_impl: native
aug_repeats: 0
aug_splits: 0
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
channels_last: false
checkpoint_hist: 10
class_map: ''
clip_grad: null
clip_mode: norm
color_jitter: 0.4
crop_pct: null
cutmix: 0.0
cutmix_minmax: null
data_dir: null
dataset: ''
dataset_download: false
decay_epochs: 90
decay_milestones:
- 90
- 180
- 270
decay_rate: 0.1
dist_bn: reduce
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
eval_metric: top1
experiment: ''
fast_norm: false
fuser: ''
gp: null
grad_accum_steps: 1
grad_checkpointing: false
head_init_bias: null
head_init_scale: null
hflip: 0.5
in_chans: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd_loss: false
layer_decay: null
local_rank: 0
log_interval: 50
lr_base: 0.1
lr_base_scale: ''
lr_base_size: 256
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
mixup: 0.0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
model_kwargs: {}
no_aug: false
no_ddp_bb: false
no_prefetcher: false
no_resume_opt: false
num_classes: null
opt_betas: null
opt_eps: null
opt_kwargs: {}
patience_epochs: 10
pin_mem: false
pretrained: false
pretrained_path: null
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.0
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched_on_updates: false
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
synchronize_step: false
torchcompile: null
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: null
vflip: 0.0
warmup_prefix: false
worker_seeding: all
workers: 4